/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gidas;

/**
 *
 * @author ITCDD-PROGRAMMING
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_family_name_head = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbb_other_dependents = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbb_sex = new javax.swing.JComboBox<>();
        txt_age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbb_status = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_occupation = new javax.swing.JTextField();
        txt_spouse_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_spouse_age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_no_of_children_girl = new javax.swing.JTextField();
        txt_no_of_children_boy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_spouse_occupation = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbb_status_of_employment = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Spouse Name (Pangalan sa asawa) :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        jPanel1.add(txt_family_name_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name of Family Head :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        cbb_other_dependents.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbb_other_dependents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ginikanan", "Igsoon", "Pag-umangkon" }));
        jPanel1.add(cbb_other_dependents, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Sex :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Status :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        cbb_sex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbb_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male (lalaki)", "Female (babae)" }));
        jPanel1.add(cbb_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 290, 30));
        jPanel1.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 290, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Other dependents (Uban pang gibuhi) :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        cbb_status.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married (may asawa)", "Singel (Dalaga/Ulitawo)" }));
        jPanel1.add(cbb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 290, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Status of Employment :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Age (edad) :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        jPanel1.add(txt_occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 290, 30));
        jPanel1.add(txt_spouse_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 190, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("babaye");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Occupation (Trabaho) :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel1.add(txt_spouse_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 190, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Occupation (Trabaho) :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Age (edad) :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));
        jPanel1.add(txt_no_of_children_girl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 80, 30));
        jPanel1.add(txt_no_of_children_boy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 70, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("lalaki/");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("No. of Children (Pila kabuok ang anak) :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        jPanel1.add(txt_spouse_occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 190, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Address :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        cbb_status_of_employment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbb_status_of_employment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wage (Suweldo)", "Self-employed (Kaugalingong Panginabuhian)" }));
        jPanel1.add(cbb_status_of_employment, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 290, 30));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_save.setText("Next");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 570, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbb_other_dependents;
    private javax.swing.JComboBox<String> cbb_sex;
    private javax.swing.JComboBox<String> cbb_status;
    private javax.swing.JComboBox<String> cbb_status_of_employment;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_family_name_head;
    private javax.swing.JTextField txt_no_of_children_boy;
    private javax.swing.JTextField txt_no_of_children_girl;
    private javax.swing.JTextField txt_occupation;
    private javax.swing.JTextField txt_spouse_age;
    private javax.swing.JTextField txt_spouse_name;
    private javax.swing.JTextField txt_spouse_occupation;
    // End of variables declaration//GEN-END:variables
}
